### ISSUE TITLE
Build projects dependent on other ROS packages with build-cmake-project

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/github-actions#40]
I'd like to install my project on Github Actions with [`build-cmake-project`](https://github.com/jrl-umi3218/github-actions/tree/master/build-cmake-project), but it depends on other ROS packages, so the ROS setup script needs to be loaded (e.g. `source /opt/ros/noetic/setup.bash`) before executing installation commands. Is this possible with [`build-cmake-project`](https://github.com/jrl-umi3218/github-actions/tree/master/build-cmake-project)?

More specifically, I'm encountering the above issue with the installation of [this project](https://github.com/isri-aist/McRtcTactileSensorPlugin#installation-procedure), which itself is not a ROS package, but depends on other ROS packages.

**Comment by gergondet** [comment]
Hi @mmurooka 

Looking at this log: https://github.com/isri-aist/McRtcTactileSensorPlugin/actions/runs/5401929615/jobs/9812460540

You can see the following:

![Screenshot from 2023-06-29 11-01-42](https://github.com/jrl-umi3218/github-actions/assets/473543/cf2c88e2-2b60-4113-bfb5-b1936327f79d)

The ROS environment itself is setup. The CI is failing to find the package that you built in a separate workspace.

You can add the package via the jrl-umi3218/github-actions/install-dependencies action (see https://github.com/jrl-umi3218/github-actions/tree/master/install-dependencies#workspace) and this should add the workspace to the environment as well. In fact, you get the base ROS environment setup because you are using the ros entry in your initial `install-dependencies` "call".

**Comment by mmurooka** [comment]
Thank you, the error was solved with the method you suggested!

> In fact, you get the base ROS environment setup because you are using the ros entry in your initial install-dependencies "call".

Yes, in my first comment I gave `source /opt/ros/noetic/setup.bash` as an example, but actually I wanted `source ~/my_workspace/devel/setup.bash`. The workspace parameter of the install-dependencies action solved this requirement.
